CREATE OR REPLACE TRIGGER t
  BEFORE
    INSERT OR
    UPDATE OF AMOUNT OR
    DELETE
  ON OPERATIONS
BEGIN
  CASE
    WHEN INSERTING THEN
      DBMS_OUTPUT.PUT_LINE('Inserting');
    WHEN UPDATING('AMOUNT') THEN
      DBMS_OUTPUT.PUT_LINE('Updating amount');
    WHEN UPDATING('department_id') THEN
      DBMS_OUTPUT.PUT_LINE('Updating department ID');
    WHEN DELETING THEN
      DBMS_OUTPUT.PUT_LINE('Deleting');
  END CASE;
END;